import { buildModule } from "@nomicfoundation/hardhat-ignition/modules";
import { parseEther } from "ethers";

export default buildModule(
  "RentalScoreModule",
  (m) => {
    // const initialOwner = m.getAccount(0); // Getting the first account generated by hardhat
    // const initialOwner = m.getParameter("initialOwner");
    const payDate = Math.floor(new Date('10/05/2025').getTime() / 1000);
    const expectedRent = BigInt(parseEther("0.01")).toString(); // 0.01 ETH   
    const renter = "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
    const landlord = "0xdD2FD4581271e230360230F9337D5c0430Bf44C0"; // Second but last hardhat node account
    const startDate = Math.floor(new Date('10/02/2025').getTime() / 1000);
    const endDate = Math.floor(new Date('10/02/2027').getTime() / 1000);
    const location = "34 rue Feutrier 75018 Paris"


    const vault = m.contract("Rental", [payDate, expectedRent, renter, landlord, startDate, endDate, location]);

    return { vault };
  }
);