import { buildModule } from "@nomicfoundation/hardhat-ignition/modules";
import { parseEther } from "ethers";

export default buildModule(
  "RentalScoreModule",
  (m) => {
    // const initialOwner = m.getAccount(0); // Getting the first account generated by hardhat
    // const initialOwner = m.getParameter("initialOwner");
    const payDate = Math.floor(new Date('09/04/2025').getTime() / 1000);
    const expectedRent = BigInt(parseEther("0.01")).toString(); // 0.01 ETH   
    const renter = "0xd9e8294515669AD69068d97Bc61Ff58ed87218E3"  // Berarchain testnet account
    const landlord = "0xe930e1c67410e8807C3aD8de503a98e74C94b17e"; // EthDam account
    const startDate = Math.floor(new Date('08/30/2025').getTime() / 1000);
    const endDate = Math.floor(new Date('08/30/2027').getTime() / 1000);
    const location = "34 rue Feutrier 75018 Paris"

    const vault = m.contract("Rental", [payDate, expectedRent, renter, landlord, startDate, endDate, location]);

    return { vault };
  }
);